// <auto-generated />
using System;
using System.Collections.Generic;
using Eawv.Service.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Eawv.Service.Migrations
{
    [DbContext(typeof(EawvContext))]
    [Migration("20181205103925_SeedCountries")]
    partial class SeedCountries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.BallotDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<byte[]>("Document")
                        .IsRequired();

                    b.Property<Guid>("ElectionId");

                    b.Property<Guid?>("ListId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ListId");

                    b.ToTable("BallotDocuments");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .IsRequired();

                    b.Property<string>("AddressLine2");

                    b.Property<string>("CallName")
                        .IsRequired();

                    b.Property<Guid?>("CandidateId");

                    b.Property<string>("CandidateReference")
                        .IsRequired();

                    b.Property<string>("CandidateTextInfo")
                        .IsRequired();

                    b.Property<Guid>("CountryId");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("DwellingNumber");

                    b.Property<string>("FamilyName")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("HouseNumber");

                    b.Property<bool>("Incumbent");

                    b.Property<Guid?>("ListId");

                    b.Property<string>("Locality");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("OccupationalTitle");

                    b.Property<string>("Origin");

                    b.Property<string>("PartyTenantId")
                        .IsRequired();

                    b.Property<int>("Sex");

                    b.Property<int>("State");

                    b.Property<string>("Street")
                        .IsRequired();

                    b.Property<string>("Town")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<string>("ZipCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ListId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IsoName")
                        .IsRequired();

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("IsoName");

                    b.ToTable("Countries");

                    b.HasData(
                        new { Id = new Guid("ecc6d00b-feab-4d86-91a3-183a89202d9b"), IsoName = "AF", ShortName = "Afghanistan" },
                        new { Id = new Guid("38681d80-158b-47fb-8fc9-8b4e6964d426"), IsoName = "EG", ShortName = "Ägypten" },
                        new { Id = new Guid("7363bdff-b632-4077-9c64-aa45569675aa"), IsoName = "AL", ShortName = "Albanien" },
                        new { Id = new Guid("1cf5cafb-224b-4b9a-b384-731a9fb4dbff"), IsoName = "DZ", ShortName = "Algerien" },
                        new { Id = new Guid("277ef36a-8060-4bf4-909a-daa89a9138a7"), IsoName = "AD", ShortName = "Andorra" },
                        new { Id = new Guid("6a58399e-23be-42b4-8251-cdf868db53c3"), IsoName = "AO", ShortName = "Angola" },
                        new { Id = new Guid("7feed28b-d4c6-408e-abfb-0d653a6b215d"), IsoName = "AG", ShortName = "Antigua und Barbuda" },
                        new { Id = new Guid("df7ac2e7-42ef-4a67-9aac-3bf51f0d6eaf"), IsoName = "GQ", ShortName = "Äquatorialguinea" },
                        new { Id = new Guid("00ff8a5e-0c45-447d-9465-75f43475a9a4"), IsoName = "AR", ShortName = "Argentinien" },
                        new { Id = new Guid("e77ea5dd-934c-4982-a014-c1a9d1964cd2"), IsoName = "AM", ShortName = "Armenien" },
                        new { Id = new Guid("ee4b2340-81ac-450e-968d-1f6821cf467e"), IsoName = "AZ", ShortName = "Aserbaidschan" },
                        new { Id = new Guid("b84393d5-e9b0-435d-835a-7e6b54afb2a0"), IsoName = "ET", ShortName = "Äthiopien" },
                        new { Id = new Guid("b0cccb7d-6ca3-4497-99a9-0ea9a29fc68e"), IsoName = "AU", ShortName = "Australien" },
                        new { Id = new Guid("872e883e-97c5-43ab-b0a1-12b8e9b26ee6"), IsoName = "BS", ShortName = "Bahamas" },
                        new { Id = new Guid("d9016110-e68d-4719-8377-9f4854b46565"), IsoName = "BH", ShortName = "Bahrain" },
                        new { Id = new Guid("28e676a0-4b02-49eb-8ce6-02eb4df8b585"), IsoName = "BD", ShortName = "Bangladesch" },
                        new { Id = new Guid("ac6e2f59-5ef9-4d82-bd73-ee0fe3c8067a"), IsoName = "BB", ShortName = "Barbados" },
                        new { Id = new Guid("6d57d280-03b2-4b21-a117-598fb9d56b44"), IsoName = "BY", ShortName = "Weißrussland" },
                        new { Id = new Guid("05dc3d63-99a6-4bed-88de-9067b71bd8ac"), IsoName = "BE", ShortName = "Belgien" },
                        new { Id = new Guid("462269a7-68bf-4cb4-87c7-19786e981449"), IsoName = "BZ", ShortName = "Belize" },
                        new { Id = new Guid("abc89707-ef85-41a9-a733-17eec4c3f470"), IsoName = "BJ", ShortName = "Benin" },
                        new { Id = new Guid("40d00168-1125-4c0a-a5d5-f3e130b66cab"), IsoName = "BT", ShortName = "Bhutan" },
                        new { Id = new Guid("492be6c3-388a-4fe2-a04b-cfb0cd9ec644"), IsoName = "BO", ShortName = "Bolivien" },
                        new { Id = new Guid("6e79a485-8e7d-4823-8a2f-25b1595e645a"), IsoName = "BA", ShortName = "Bosnien und Herzegowina" },
                        new { Id = new Guid("2909887c-2913-48b5-a6df-1d294c78a5f7"), IsoName = "BW", ShortName = "Botswana" },
                        new { Id = new Guid("aaeb5b33-ab0a-4919-ba05-dc1c30f6bed1"), IsoName = "BR", ShortName = "Brasilien" },
                        new { Id = new Guid("ba9c4c96-8f36-4c5c-946e-49c57c973419"), IsoName = "BN", ShortName = "Brunei" },
                        new { Id = new Guid("68ac7a77-217f-4fb9-a957-1d574b3848a2"), IsoName = "BG", ShortName = "Bulgarien" },
                        new { Id = new Guid("4660fb9e-aaf0-4378-b695-141da78c74d7"), IsoName = "BF", ShortName = "Burkina Faso" },
                        new { Id = new Guid("317f565f-b0cc-4e64-a497-7d55ce2b6e6e"), IsoName = "BI", ShortName = "Burundi" },
                        new { Id = new Guid("9014b80a-a539-4d86-9063-bfa4361fed12"), IsoName = "CL", ShortName = "Chile" },
                        new { Id = new Guid("556f6011-3ae0-47a1-a8c9-6a5c42764fe0"), IsoName = "CN", ShortName = "Volksrepublik China" },
                        new { Id = new Guid("9c6f3c6e-2f6e-4987-9e71-bfece6479fa7"), IsoName = "CR", ShortName = "Costa Rica" },
                        new { Id = new Guid("96a4285a-7138-473c-969b-8cd316f9506e"), IsoName = "CI", ShortName = "Elfenbeinküste" },
                        new { Id = new Guid("492bcfda-24ab-4fd9-9103-1ddf3f200823"), IsoName = "DK", ShortName = "Dänemark" },
                        new { Id = new Guid("46a2d622-be48-4534-b198-da740eed53f0"), IsoName = "DE", ShortName = "Deutschland" },
                        new { Id = new Guid("febba22b-6d8f-4ace-9aba-4f68c71a420d"), IsoName = "DM", ShortName = "Dominica" },
                        new { Id = new Guid("a3376354-b5d2-4530-9715-b8d2d23d2806"), IsoName = "DO", ShortName = "Dominikanische Republik" },
                        new { Id = new Guid("d0011d00-5d18-4f1a-9adf-4d0af646e1ef"), IsoName = "DJ", ShortName = "Dschibuti" },
                        new { Id = new Guid("b74dd0af-a230-4f16-b5e0-601da51e7a03"), IsoName = "EC", ShortName = "Ecuador" },
                        new { Id = new Guid("d2f48a0b-a017-4865-b6b8-8c58e93e964b"), IsoName = "SV", ShortName = "El Salvador" },
                        new { Id = new Guid("60e30952-33d9-4371-870d-926eb9f04609"), IsoName = "ER", ShortName = "Eritrea" },
                        new { Id = new Guid("ed9f2cad-9ffa-41c2-b69e-b0ad1c1e9cf3"), IsoName = "EE", ShortName = "Estland" },
                        new { Id = new Guid("21837aba-2a53-4bcd-a1f5-57cfb36034d0"), IsoName = "FJ", ShortName = "Fidschi" },
                        new { Id = new Guid("a6be47d3-aaf1-4521-9282-2dda10910e3b"), IsoName = "FI", ShortName = "Finnland" },
                        new { Id = new Guid("0bb61630-85af-48c5-a357-79dfae9ef75b"), IsoName = "FR", ShortName = "Frankreich" },
                        new { Id = new Guid("16128ca5-1467-4fe7-a837-e2ebd232d4bd"), IsoName = "GA", ShortName = "Gabun" },
                        new { Id = new Guid("f6a9a1db-3da0-4b20-8ef7-6ce24f9d1c20"), IsoName = "GM", ShortName = "Gambia" },
                        new { Id = new Guid("a6ac9c03-00dd-4b9d-9109-1e029f0fe14c"), IsoName = "GE", ShortName = "Georgien" },
                        new { Id = new Guid("efc45aa3-be8a-4210-9153-5c03e7e14b78"), IsoName = "GH", ShortName = "Ghana" },
                        new { Id = new Guid("455f6b72-2981-4b2c-a9f4-3fd5fc4514da"), IsoName = "GD", ShortName = "Grenada" },
                        new { Id = new Guid("994b8004-0fee-4169-b29a-179ae107513f"), IsoName = "GR", ShortName = "Griechenland" },
                        new { Id = new Guid("e0c4fe9b-7702-46d3-b7a8-5a6be438d3e3"), IsoName = "GT", ShortName = "Guatemala" },
                        new { Id = new Guid("a6d65649-d179-4f9d-b2fc-494d6b11a701"), IsoName = "GN", ShortName = "Guinea" },
                        new { Id = new Guid("bfe6be6d-d528-43ac-afa0-4ddb46d01c2c"), IsoName = "GW", ShortName = "Guinea-Bissau" },
                        new { Id = new Guid("2d0e83bf-02d4-45aa-aeb4-fbd02abdfdfd"), IsoName = "GY", ShortName = "Guyana" },
                        new { Id = new Guid("1a2afa35-deeb-4244-a120-0d51eeaac924"), IsoName = "HT", ShortName = "Haiti" },
                        new { Id = new Guid("868b24fd-47fe-40c4-bcb1-02030930e1a2"), IsoName = "HN", ShortName = "Honduras" },
                        new { Id = new Guid("11a4f157-76b7-4e50-b07a-906ca280c901"), IsoName = "IN", ShortName = "Indien" },
                        new { Id = new Guid("3817357f-205f-4dc8-a537-2712ca8092a7"), IsoName = "ID", ShortName = "Indonesien" },
                        new { Id = new Guid("ff6b4b96-e738-4ee2-bdae-bae8329f5b83"), IsoName = "IQ", ShortName = "Irak" },
                        new { Id = new Guid("40cf9ee7-88db-4324-b6b7-ccb6d18d3d16"), IsoName = "IR", ShortName = "Iran" },
                        new { Id = new Guid("6b96fe1a-4ea3-495a-8859-214e19b06ad7"), IsoName = "IE", ShortName = "Irland" },
                        new { Id = new Guid("254cb18d-25f2-4771-8a77-d935db5ce995"), IsoName = "IS", ShortName = "Island" },
                        new { Id = new Guid("4c60f97d-9c8f-481f-9dbe-d19bdc2ffcd1"), IsoName = "IL", ShortName = "Israel" },
                        new { Id = new Guid("ed6e0202-2927-4071-b05b-c0723dcd910a"), IsoName = "IT", ShortName = "Italien" },
                        new { Id = new Guid("70f0a940-5e5a-4f21-b331-ac115f867260"), IsoName = "JM", ShortName = "Jamaika" },
                        new { Id = new Guid("76b789fb-2be8-450b-baaf-cfee69c2638d"), IsoName = "JP", ShortName = "Japan" },
                        new { Id = new Guid("3c000074-f54a-4c65-a261-f68502b28efa"), IsoName = "YE", ShortName = "Jemen" },
                        new { Id = new Guid("de33a841-cd13-4a48-97c0-08900ebf38ea"), IsoName = "JO", ShortName = "Jordanien" },
                        new { Id = new Guid("faf649cc-24ca-4352-aea2-b092e63dcb70"), IsoName = "KH", ShortName = "Kambodscha" },
                        new { Id = new Guid("3a21b718-016b-4b3e-a34e-3b10c9d09b42"), IsoName = "CM", ShortName = "Kamerun" },
                        new { Id = new Guid("f9618263-3623-41a4-a899-f9ef11306bd0"), IsoName = "CA", ShortName = "Kanada" },
                        new { Id = new Guid("1637a65a-373f-4e24-8d3c-f3eafd267efb"), IsoName = "CV", ShortName = "Kap Verde" },
                        new { Id = new Guid("d8352538-d392-40a5-bdba-36ea1eaaff8c"), IsoName = "KZ", ShortName = "Kasachstan" },
                        new { Id = new Guid("de46776d-c688-42eb-89ff-41ac530aec76"), IsoName = "QA", ShortName = "Katar" },
                        new { Id = new Guid("02fce2a2-8fdf-40d2-99a2-293eee564dd2"), IsoName = "KE", ShortName = "Kenia" },
                        new { Id = new Guid("8307270c-1fd9-4a63-8d87-c8d5dec8b523"), IsoName = "KG", ShortName = "Kirgisistan" },
                        new { Id = new Guid("13de7789-8c6c-4081-bbeb-ed3490ce77ed"), IsoName = "KI", ShortName = "Kiribati" },
                        new { Id = new Guid("7fd18f61-96c2-4928-9a51-8cd927ed250b"), IsoName = "CO", ShortName = "Kolumbien" },
                        new { Id = new Guid("98d48959-0052-4064-b738-a4fb744a4fad"), IsoName = "KM", ShortName = "Komoren" },
                        new { Id = new Guid("0489be8a-6478-4e2a-a870-3eacf161b3a9"), IsoName = "CD", ShortName = "Kongo, Demokratische Republik" },
                        new { Id = new Guid("cf46817c-2b0d-42c8-b6f6-21d7ea82c917"), IsoName = "CG", ShortName = "Kongo, Republik" },
                        new { Id = new Guid("f8bc10bb-758a-4048-9fe2-84e6767f7b77"), IsoName = "KP", ShortName = "Korea, Nord" },
                        new { Id = new Guid("1214e4cc-7ca6-44a1-90b9-c9a5a949ac80"), IsoName = "KR", ShortName = "Korea, Süd" },
                        new { Id = new Guid("743df98c-1ebe-4180-8ab7-3bc088bc62d3"), IsoName = "HR", ShortName = "Kroatien" },
                        new { Id = new Guid("ba0ea949-bdfa-4d6a-a602-2734a579480c"), IsoName = "CU", ShortName = "Kuba" },
                        new { Id = new Guid("27368aff-0f63-4471-9655-0f9834c95365"), IsoName = "KW", ShortName = "Kuwait" },
                        new { Id = new Guid("95a40b83-9a07-4099-9e91-0ffd6f4b818e"), IsoName = "LA", ShortName = "Laos" },
                        new { Id = new Guid("8105c97c-6140-46cc-8f43-2e757d73e473"), IsoName = "LS", ShortName = "Lesotho" },
                        new { Id = new Guid("1caf90c7-bfaa-40a4-bc34-69866eff3e8c"), IsoName = "LV", ShortName = "Lettland" },
                        new { Id = new Guid("8aa2f8ed-e534-4cc9-90be-c3be401c5982"), IsoName = "LB", ShortName = "Libanon" },
                        new { Id = new Guid("cf9d80ee-db23-4552-bf51-4d741a2c9f9d"), IsoName = "LR", ShortName = "Liberia" },
                        new { Id = new Guid("9d9836e2-18e2-404e-a01a-251485ee5a19"), IsoName = "LY", ShortName = "Libyen" },
                        new { Id = new Guid("d480c63d-20f6-4009-8ced-c14e8e0fe650"), IsoName = "LI", ShortName = "Liechtenstein" },
                        new { Id = new Guid("e9344538-77e7-4751-99fe-3c4fcaa392f1"), IsoName = "LT", ShortName = "Litauen" },
                        new { Id = new Guid("44c27376-e3ba-4626-b3be-e69a07500343"), IsoName = "LU", ShortName = "Luxemburg" },
                        new { Id = new Guid("ba34ffd8-0e04-4edf-b756-1fbdb3cf598e"), IsoName = "MG", ShortName = "Madagaskar" },
                        new { Id = new Guid("a18af771-f573-43d4-8303-41df09bbd821"), IsoName = "MW", ShortName = "Malawi" },
                        new { Id = new Guid("7a53d498-f246-48f6-b664-ae68b05b2737"), IsoName = "MY", ShortName = "Malaysia" },
                        new { Id = new Guid("37eb5b71-1303-476b-9fa4-9ebe63d14408"), IsoName = "MV", ShortName = "Malediven" },
                        new { Id = new Guid("2da6babf-99e9-4405-849b-a9accce87769"), IsoName = "ML", ShortName = "Mali" },
                        new { Id = new Guid("18ac8947-46e3-4fdb-aa82-daba865d4367"), IsoName = "MT", ShortName = "Malta" },
                        new { Id = new Guid("8ecb90e6-2d36-44f4-a1eb-20e73d3ae2ac"), IsoName = "MA", ShortName = "Marokko" },
                        new { Id = new Guid("72294df2-bd5b-45ed-bb81-e958a5d132b4"), IsoName = "MH", ShortName = "Marshallinseln" },
                        new { Id = new Guid("3700fc40-17e0-41b4-ae8e-b7e1d842e596"), IsoName = "MR", ShortName = "Mauretanien" },
                        new { Id = new Guid("6ddf40b4-ddcb-41c0-b57b-aa9b90fbda35"), IsoName = "MU", ShortName = "Mauritius" },
                        new { Id = new Guid("8fb0515e-71d5-441f-85f9-6b84ac46daf1"), IsoName = "MK", ShortName = "Mazedonien" },
                        new { Id = new Guid("4c718c30-57fa-4b8f-8594-c1b50f0ebf4a"), IsoName = "MX", ShortName = "Mexiko" },
                        new { Id = new Guid("51a106af-fdd1-4aad-a58e-faa182e3a55f"), IsoName = "FM", ShortName = "Mikronesien" },
                        new { Id = new Guid("725a19cf-35d0-43bd-b6a3-e18a8b520b3b"), IsoName = "MD", ShortName = "Moldau" },
                        new { Id = new Guid("b91f0a78-c7bf-4a67-99cb-e304d8071fc3"), IsoName = "MC", ShortName = "Monaco" },
                        new { Id = new Guid("4ca0a4dc-f927-42c6-bbb5-c83149ac38a8"), IsoName = "MN", ShortName = "Mongolei" },
                        new { Id = new Guid("fa35e999-47c8-4265-8a28-d75df5a3c688"), IsoName = "ME", ShortName = "Montenegro" },
                        new { Id = new Guid("d5fa56b3-a3b2-4059-a65c-41118cb5ccb1"), IsoName = "MZ", ShortName = "Mosambik" },
                        new { Id = new Guid("04817276-89bf-49d4-b13e-b605d947f8e9"), IsoName = "MM", ShortName = "Myanmar" },
                        new { Id = new Guid("d52efd96-ce56-4ec8-b95a-69d59efa6a9b"), IsoName = "NA", ShortName = "Namibia" },
                        new { Id = new Guid("0b1c1f05-0e0b-409b-ad8d-5e5e81e1a054"), IsoName = "NR", ShortName = "Nauru" },
                        new { Id = new Guid("fbebb07c-432c-4e17-897d-3aac1351b2b9"), IsoName = "NP", ShortName = "Nepal" },
                        new { Id = new Guid("7d67e03b-da05-4c2b-b5d3-b944b2070624"), IsoName = "NZ", ShortName = "Neuseeland" },
                        new { Id = new Guid("b6ada799-8621-4fe6-b6f5-1b279c20c1a3"), IsoName = "NI", ShortName = "Nicaragua" },
                        new { Id = new Guid("c2163f49-3e56-494b-b98b-c968c21dbc98"), IsoName = "NL", ShortName = "Niederlande" },
                        new { Id = new Guid("b541869b-ab67-41a6-b1ac-8905f921519b"), IsoName = "NE", ShortName = "Niger" },
                        new { Id = new Guid("f1bf1a1f-bd22-42e1-a2e2-b63cbfcfaba8"), IsoName = "NG", ShortName = "Nigeria" },
                        new { Id = new Guid("f938f7f1-7a96-478c-9273-518931935dcf"), IsoName = "NO", ShortName = "Norwegen" },
                        new { Id = new Guid("01b960a4-06d5-47b2-ae59-ca5d71dad2c3"), IsoName = "OM", ShortName = "Oman" },
                        new { Id = new Guid("5d55ede0-e514-4f93-a247-b469f212de47"), IsoName = "AT", ShortName = "Österreich" },
                        new { Id = new Guid("0c18041a-e88f-40e6-a746-12b946a1af12"), IsoName = "TL", ShortName = "Osttimor" },
                        new { Id = new Guid("849712a5-6c02-484e-82dd-00ab426df0d7"), IsoName = "PK", ShortName = "Pakistan" },
                        new { Id = new Guid("3776ac9a-c830-4815-a88b-7f98a9110bfd"), IsoName = "PW", ShortName = "Palau" },
                        new { Id = new Guid("85264237-391c-4c85-8255-241f4293364a"), IsoName = "PA", ShortName = "Panama" },
                        new { Id = new Guid("ecc27715-f9c5-487c-b20b-e5563aa8597c"), IsoName = "PG", ShortName = "Papua-Neuguinea" },
                        new { Id = new Guid("8ca26674-1675-49ba-924e-70be3c76b0e6"), IsoName = "PY", ShortName = "Paraguay" },
                        new { Id = new Guid("1a854f8e-1561-404d-bdbd-25e11823cf13"), IsoName = "PE", ShortName = "Peru" },
                        new { Id = new Guid("14e5a5ce-1a36-4eff-bf4e-55e820d3c54d"), IsoName = "PH", ShortName = "Philippinen" },
                        new { Id = new Guid("463c2bce-9590-4cf4-99d2-6d6c04c1a733"), IsoName = "PL", ShortName = "Polen" },
                        new { Id = new Guid("551f0bf8-cff1-4d9f-84f1-42aa2d6a8bf1"), IsoName = "PT", ShortName = "Portugal" },
                        new { Id = new Guid("07794061-cbc5-4300-be5d-6e843f40a24b"), IsoName = "RW", ShortName = "Ruanda" },
                        new { Id = new Guid("82ed1cc2-6d73-41b3-a936-e5782ffd24f3"), IsoName = "RO", ShortName = "Rumänien" },
                        new { Id = new Guid("c8ab44f0-9ab5-498b-90a9-afb98be191a7"), IsoName = "RU", ShortName = "Russland" },
                        new { Id = new Guid("b9da0184-3f81-4c1b-83d6-1303f1dfd0c4"), IsoName = "SB", ShortName = "Salomonen" },
                        new { Id = new Guid("6e0593ce-dc28-4abf-b95e-2733f252cc63"), IsoName = "ZM", ShortName = "Sambia" },
                        new { Id = new Guid("8cc6c651-8b04-451e-b53a-a3e6fad6d674"), IsoName = "WS", ShortName = "Samoa" },
                        new { Id = new Guid("4afeb32a-1f8b-4f16-8a1f-8ba423c5f097"), IsoName = "SM", ShortName = "San Marino" },
                        new { Id = new Guid("b2be943d-bbeb-4525-a434-7c2c4d468a84"), IsoName = "ST", ShortName = "São Tomé und Príncipe" },
                        new { Id = new Guid("ad2337dc-9bea-4ac9-bd3b-4415e2ea7a22"), IsoName = "SA", ShortName = "Saudi-Arabien" },
                        new { Id = new Guid("52e6afd6-fb5c-498a-9877-ba61933616fd"), IsoName = "SE", ShortName = "Schweden" },
                        new { Id = new Guid("74c01d6c-7d47-4405-a670-5acb43b4dd1e"), IsoName = "CH", ShortName = "Schweiz" },
                        new { Id = new Guid("0cc9e3a3-5fb0-4924-aa4e-cd3c5cd469ad"), IsoName = "SN", ShortName = "Senegal" },
                        new { Id = new Guid("b2494972-3d22-4a69-aa99-00b9deba5743"), IsoName = "RS", ShortName = "Serbien" },
                        new { Id = new Guid("62146e4e-582a-4b0f-849a-c67a670a2c94"), IsoName = "SC", ShortName = "Seychellen" },
                        new { Id = new Guid("4d699758-4de5-4bac-9c33-b8a20209961b"), IsoName = "SL", ShortName = "Sierra Leone" },
                        new { Id = new Guid("f20b7be1-4620-41b6-8c58-64cad1a4ed45"), IsoName = "ZW", ShortName = "Simbabwe" },
                        new { Id = new Guid("620b5def-4e93-41de-81c3-80bf1f5d1df3"), IsoName = "SG", ShortName = "Singapur" },
                        new { Id = new Guid("3c7adb00-378d-4961-8b89-eb549da5a597"), IsoName = "SK", ShortName = "Slowakei" },
                        new { Id = new Guid("17b71ef9-48a2-44c5-bd72-bb89a2696f72"), IsoName = "SI", ShortName = "Slowenien" },
                        new { Id = new Guid("b83585fb-3ccc-4fe4-94c8-ad1ccea88a4b"), IsoName = "SO", ShortName = "Somalia" },
                        new { Id = new Guid("18f8cbcb-24fb-490a-a1fd-2f517712f750"), IsoName = "ES", ShortName = "Spanien" },
                        new { Id = new Guid("4af95157-6913-4176-af72-d06e1744320c"), IsoName = "LK", ShortName = "Sri Lanka" },
                        new { Id = new Guid("f569abc9-a024-40c6-8aa8-7242f99e9840"), IsoName = "KN", ShortName = "St. Kitts und Nevis" },
                        new { Id = new Guid("1ab3ee5f-02f4-4ec2-88c1-76ce885f24d1"), IsoName = "LC", ShortName = "St. Lucia" },
                        new { Id = new Guid("1a3d57c7-280e-4240-b06a-ad3733fdb6c8"), IsoName = "VC", ShortName = "St. Vincent und die Grenadinen" },
                        new { Id = new Guid("9daeae0a-6d30-4690-8380-da141ae80692"), IsoName = "ZA", ShortName = "Südafrika" },
                        new { Id = new Guid("f2951037-acc8-49e6-97b3-925267c842cd"), IsoName = "SD", ShortName = "Sudan" },
                        new { Id = new Guid("911b986b-2f17-4fed-bcfc-63c1d0f22a3d"), IsoName = "SS", ShortName = "Südsudan" },
                        new { Id = new Guid("af39012b-ac0e-413c-9342-2a47b9012d33"), IsoName = "SR", ShortName = "Suriname" },
                        new { Id = new Guid("065e3121-5835-4a66-8c84-d5afbc484efa"), IsoName = "SZ", ShortName = "Swasiland" },
                        new { Id = new Guid("088026a2-f826-4a58-a66b-e37e53e2b08a"), IsoName = "SY", ShortName = "Syrien" },
                        new { Id = new Guid("d6adedbb-f764-4688-92a9-1a61d5c27d1c"), IsoName = "TJ", ShortName = "Tadschikistan" },
                        new { Id = new Guid("2b21395c-658b-498b-9d36-4dbda62e9f09"), IsoName = "TZ", ShortName = "Tansania" },
                        new { Id = new Guid("fde2add7-a7d8-49f1-a680-7b03720afd05"), IsoName = "TH", ShortName = "Thailand" },
                        new { Id = new Guid("a533c18e-9a76-4a87-ae56-4ea5da4635ce"), IsoName = "TG", ShortName = "Togo" },
                        new { Id = new Guid("6a2510e5-cd3e-438b-8f36-3ae1aa99bcb0"), IsoName = "TO", ShortName = "Tonga" },
                        new { Id = new Guid("1ec005cb-c9be-4af0-b8d5-98e8949bdb5e"), IsoName = "TT", ShortName = "Trinidad und Tobago" },
                        new { Id = new Guid("b4f16045-030f-4bcf-8d9e-0e197c094f44"), IsoName = "TD", ShortName = "Tschad" },
                        new { Id = new Guid("a1bc826d-308d-4599-89ad-bcc9a87f1746"), IsoName = "CZ", ShortName = "Tschechien" },
                        new { Id = new Guid("83768fd8-4bd7-46a7-8455-ed20a56d8f34"), IsoName = "TN", ShortName = "Tunesien" },
                        new { Id = new Guid("9ca83f25-0ab4-432e-ad7c-3869a8da5c8d"), IsoName = "TR", ShortName = "Türkei" },
                        new { Id = new Guid("5743e603-eea3-4580-9203-e3971a94f16d"), IsoName = "TM", ShortName = "Turkmenistan" },
                        new { Id = new Guid("c84a5461-ea30-4cc4-b8bb-a25bb259d398"), IsoName = "TV", ShortName = "Tuvalu" },
                        new { Id = new Guid("a8fb382f-73f3-4f75-a8b2-11ec52eb985b"), IsoName = "UG", ShortName = "Uganda" },
                        new { Id = new Guid("e03595cc-44c9-4127-93fe-5604ff671b92"), IsoName = "UA", ShortName = "Ukraine" },
                        new { Id = new Guid("10da7615-31ac-4678-a58e-5886f5e23624"), IsoName = "HU", ShortName = "Ungarn" },
                        new { Id = new Guid("ab6f1903-a7a6-4d1e-ac77-0e99ad0e4c73"), IsoName = "UY", ShortName = "Uruguay" },
                        new { Id = new Guid("3eeca45b-862c-487c-bf87-1a31b5163db8"), IsoName = "UZ", ShortName = "Usbekistan" },
                        new { Id = new Guid("17440274-e802-4096-af6d-36f1b8bbab8c"), IsoName = "VU", ShortName = "Vanuatu" },
                        new { Id = new Guid("d519d48b-32be-4ea4-a413-d834666e4ea7"), IsoName = "VE", ShortName = "Venezuela" },
                        new { Id = new Guid("be10a4f5-e846-4e64-8b1b-6d1b573d6618"), IsoName = "AE", ShortName = "Vereinigte Arabische Emirate" },
                        new { Id = new Guid("db88ffe2-15c5-41e7-b66e-f7a2b7564c4e"), IsoName = "US", ShortName = "Vereinigte Staaten" },
                        new { Id = new Guid("7aeccc40-f719-4797-869b-ba93162fd603"), IsoName = "GB", ShortName = "Vereinigtes Königreich" },
                        new { Id = new Guid("46638705-8484-4d44-84e4-530c8479c6cf"), IsoName = "VN", ShortName = "Vietnam" },
                        new { Id = new Guid("16317b07-593a-4c96-9f01-5153e868dfbd"), IsoName = "CF", ShortName = "Zentral­afrikanische Republik" },
                        new { Id = new Guid("a95ca444-bb2d-4483-9d17-6ec3d578f386"), IsoName = "CY", ShortName = "Zypern" }
                    );
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.DomainOfInfluence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("DomainOfInfluenceType");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OfficialId");

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.Property<string>("TenantId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DomainsOfInfluence");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.DomainOfInfluenceElection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("DomainOfInfluenceId");

                    b.Property<Guid>("ElectionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("NumberOfMandates");

                    b.HasKey("Id");

                    b.HasIndex("DomainOfInfluenceId");

                    b.HasIndex("ElectionId");

                    b.ToTable("DomainOfInfluenceElections");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ContestDate");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<int>("ElectionType");

                    b.Property<bool>("FileUploadActivated");

                    b.Property<string>("FileUploadDescription");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("NoQuorumRequired");

                    b.Property<int>("State");

                    b.Property<DateTime>("SubmissionDeadlineBegin");

                    b.Property<DateTime>("SubmissionDeadlineEnd");

                    b.Property<string>("TenantId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.ElectionQuorumExemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("ElectionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("PartyTenantId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("ElectionQuorumExemptions");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.InfoText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid?>("ElectionId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("TenantId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.Property<bool>("Visible");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("InfoTexts");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<List<string>>("DeputyUsers");

                    b.Property<string>("Description");

                    b.Property<Guid>("ElectionId");

                    b.Property<int>("Indenture");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ResponsiblePartyTenantId")
                        .IsRequired();

                    b.Property<int>("SortOrder");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.ListUnion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("ListId");

                    b.Property<string>("ListUnionDescription");

                    b.Property<Guid>("ListUnionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("ListUnionId");

                    b.ToTable("ListUnions");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.ListUnionElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("ListId");

                    b.Property<Guid>("ListUnionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("ListUnionId");

                    b.ToTable("ListUnionElements");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.MarkedElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<Guid>("ReferenceId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MarkedElements");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.BallotDocument", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("Documents")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eawv.Service.DataAccess.Entities.List")
                        .WithMany("ElectionDocuments")
                        .HasForeignKey("ListId");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.Candidate", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Country", "Country")
                        .WithMany("Candidates")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eawv.Service.DataAccess.Entities.List", "List")
                        .WithMany("Candidates")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.DomainOfInfluenceElection", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.DomainOfInfluence", "DomainOfInfluence")
                        .WithMany("ParticipatingElections")
                        .HasForeignKey("DomainOfInfluenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("DomainsOfInfluence")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.ElectionQuorumExemption", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("QuorumExemptions")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.InfoText", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("InfoTexts")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.List", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("Lists")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.ListUnion", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.List", "ReferencedList")
                        .WithMany("ListUnions")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eawv.Service.DataAccess.Entities.ListUnion", "ReferencedUnion")
                        .WithMany("ListUnionParticipations")
                        .HasForeignKey("ListUnionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.ListUnionElement", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.List", "ReferencedList")
                        .WithMany("ListUnionElements")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eawv.Service.DataAccess.Entities.ListUnion", "ReferencedUnion")
                        .WithMany("ListUnionElements")
                        .HasForeignKey("ListUnionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
