// <auto-generated />
using System;
using System.Collections.Generic;
using Eawv.Service.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Eawv.Service.Migrations
{
    [DbContext(typeof(EawvContext))]
    [Migration("20181218155233_ListSubmitDate")]
    partial class ListSubmitDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.BallotDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<byte[]>("Document")
                        .IsRequired();

                    b.Property<Guid>("ElectionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("BallotDocuments");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BallotFamilyName")
                        .IsRequired();

                    b.Property<string>("BallotFirstName")
                        .IsRequired();

                    b.Property<string>("BallotOccupationalTitle")
                        .IsRequired();

                    b.Property<bool>("Cloned");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FamilyName")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("HouseNumber");

                    b.Property<bool>("Incumbent");

                    b.Property<int>("Index");

                    b.Property<Guid>("ListId");

                    b.Property<string>("Locality")
                        .IsRequired();

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("OccupationalTitle")
                        .IsRequired();

                    b.Property<string>("Origin");

                    b.Property<string>("OriginCanton");

                    b.Property<int>("Sex");

                    b.Property<string>("Street")
                        .IsRequired();

                    b.Property<string>("ZipCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.DomainOfInfluence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("DomainOfInfluenceType");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OfficialId")
                        .IsRequired();

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.Property<string>("TenantId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DomainsOfInfluence");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.DomainOfInfluenceElection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("DomainOfInfluenceId");

                    b.Property<Guid>("ElectionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("NumberOfMandates");

                    b.HasKey("Id");

                    b.HasAlternateKey("ElectionId", "DomainOfInfluenceId");

                    b.HasIndex("DomainOfInfluenceId");

                    b.ToTable("DomainOfInfluenceElections");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ContestDate");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<int>("ElectionType");

                    b.Property<bool>("FileUploadActivated");

                    b.Property<string>("FileUploadDescription");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("QuorumSignaturesCount");

                    b.Property<int>("State");

                    b.Property<DateTime>("SubmissionDeadlineBegin");

                    b.Property<DateTime>("SubmissionDeadlineEnd");

                    b.Property<string>("TenantId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.InfoText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid?>("ElectionId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("TenantId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.Property<bool>("Visible");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("InfoTexts");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<List<string>>("DeputyUsers");

                    b.Property<string>("Description");

                    b.Property<Guid>("ElectionId");

                    b.Property<string>("Indenture");

                    b.Property<Guid?>("ListSubUnionId");

                    b.Property<Guid?>("ListUnionId");

                    b.Property<bool>("Locked");

                    b.Property<List<string>>("MemberUsers");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ResponsiblePartyTenantId")
                        .IsRequired();

                    b.Property<int>("SortOrder");

                    b.Property<int>("State");

                    b.Property<DateTime?>("SubmitDate");

                    b.Property<bool>("Validated");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ListSubUnionId");

                    b.HasIndex("ListUnionId");

                    b.HasIndex("ElectionId", "Indenture")
                        .IsUnique();

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.ListUnion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<Guid?>("RootListId");

                    b.HasKey("Id");

                    b.HasIndex("RootListId")
                        .IsUnique();

                    b.ToTable("ListUnions");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.MarkedElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CandidateId");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Field")
                        .IsRequired();

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "Field")
                        .IsUnique();

                    b.ToTable("MarkedElements");
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.TemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Filename");

                    b.Property<int>("Format");

                    b.Property<bool>("Landscape");

                    b.Property<string>("TenantId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new { Id = new Guid("7473694c-6143-646e-6964-617465732d00"), Content = @"@using Eawv.Service.DataAccess.Entities
@using RazorLight
@using System.Linq
@using System
@inherits TemplatePage<Eawv.Service.Models.TemplateServiceModels.TemplateBag>
<html>
  <head>
    <meta charset=""UTF-8"" />
    <style>
      body {
        margin: 0;
        padding: 0;
        position: relative;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 12px;
      }

      @(""@"")media only screen {
        body {
          background-color: gray;
          padding: 1cm; // default of pdf renderer
        }

        .doc {
          background-color: white;
        }
      }

      h1,
      h2,
      h3,
      h4,
      h5 {
        margin: 0;
      }

      h1 {
        margin-bottom: 1mm;
      }

      .input {
        height: 1rem;
        position: relative;
        display: inline-block;
        padding: 0 1mm;
        box-sizing: border-box;
      }
      .input .border {
        border: 1px solid #999;
        border-top: none;
        height: 1mm;
        margin-top: 3mm;
        margin: 3mm 0.5mm 0.5mm 0.5mm;
        bottom: 0;
        position: absolute;
        left: 0;
        right: 0;
      }
      input {
        border: none;
        width: 100%;
        position: relative;
        bottom: 1mm;
      }
      .inline-input {
        bottom: -.5mm;
      }

      .w-2 {
        width: 2rem;
      }
      .w-4 {
        width: 4rem;
      }
      .w-6 {
        width: 6rem;
      }
      .w-16 {
        width: 16rem;
      }

      .col-main {
        width: 19cm;
      }

      .col-right {
        width: 8.5cm;
      }

      .label {
        font-size: 1.1rem;
        font-weight: 700;
        color: #999;
        margin-right: 0.2rem;
        position: relative;
        top: -1mm;
      }

      .size-A4.landscape {
        width: 297mm;
      }

      .size-A4 {
        width: 210mm;
      }

      .hint {
        font-size: 8pt;
        color: #555;
      }

      .filled {
        background-color: #dadada;
      }

      .small {
        font-size: 7pt;
      }
      .bold {
        font-weight: 700;
      }
      .super {
        vertical-align: super;
      }

      .row {
        display: flex;
        flex-direction: row;
        margin-bottom: 0.15rem;
      }
      .col {
        display: flex;
        flex-direction: column;
      }
      .stretch {
        justify-content: stretch;
      }
      .space {
        justify-content: space-between;
      }
      .grow {
        flex-grow: 1;
      }
      .no-shrink {
        flex-shrink: 0;
      }
      .end {
        justify-content: flex-end;
      }
      .center {
        justify-content: center;
      }
      .right {
        text-align: right;
      }
      .inline {
        display: inline-block;
        margin: 0;
      }
      .fullwidth {
        width: 100%;
      }
      .spacer {
        display: inline-block;
        width: 0.5rem;
      }
      .space-bottom {
        margin-bottom: 1.5mm;
      }
      .space-right {
        margin-right: 2mm;
      }

      .upright {
        writing-mode: vertical-lr;
        transform: rotate(-180deg);
      }

      table {
        margin-bottom: 1.5mm;
      }

      table,
      th,
      td {
        font-size: 11px;
        border-collapse: collapse;
        border: 1px solid #000;
      }

      th {
        background-color: #dadada;
        vertical-align: top;
      }

      th,
      td {
        padding: 1mm;
      }

      thead tr > tr th {
        font-weight: 400;
      }

      thead {
        height: 200px;
      }
      tbody {
        background-color: #fff;
      }
      tbody td {
        border-top: 1px dashed #000;
        border-bottom: 1px dashed #000;
      }

      tbody tr {
        height: 1cm;
      }
      
      tbody tr > td.right {
        text-align: right;
      }
      
      tbody tr > td.center {
        text-align: center;
      }

      .top-no-border th,
      .top-no-border tr {
        border-top: none;
      }
      .bot-no-border {
        border-bottom: none;
      }

      .center-placeholder::placeholder {
        text-align: center;
        color: #000;
      }

      .version {
        align-items: flex-end;
        justify-content: flex-end;
        display: flex;
      }
    </style>
  </head>
  <body>
    <div class=""doc size-A4 landscape"">
      <header class=""row space"">
        <h1>@Model.Election.Name vom @Model.Election.ContestDate.ToString(""dd. MMMM y"")</h1>
        <h1>@Model.ElectionTenant.Name</h1>
      </header>
      <main>
        <div class=""row stretch"">
          <span class=""label space-right"">A</span>
          <div class=""grow"">
            <div class=""row space"">
              <div class=""row col-main"">
                <div>
                  <span class=""bold"">Bezeichnung</span> des Wahlvorschlags:
                </div>
                <div class=""grow col"">
                  <div class=""input"">
                    <input value=""@Model.List.Name""/>
                    <div class=""border""></div>
                  </div>
                </div>
              </div>
            </div>
            <div class=""row space"">
              <div class=""row col-main"">
                <div>
                  Evtl. <span class=""bold"">Präzisierung</span> nach Alter,
                  Geschlecht, Region oder Parteiflügel:
                </div>
                <div class=""input grow"">
                  <input value=""@Model.List.Description""/>
                  <div class=""border""></div>
                </div>
              </div>
            </div>
            <div class=""row col-main space"">
              <div class=""flex"">
                <span class=""bold"">Listennnummer</span> (wird vom Kanton zugeteilt):
                <div class=""input inline-input w-4"">
                  <input value=""@Model.List.Indenture""/>
                  <div class=""border""></div>
                </div>
              </div>
              @if(Model.List.SubmitDate.HasValue) 
              {
                <div class=""flex"">
                  Einreichedatum:
                  <div class=""input inline-input w-6"">
                    <input value=""@Model.List.SubmitDate.Value.ToString(""d"")""/>
                    <div class=""border""></div>
                  </div>
                  <div class=""input inline-input w-4"">
                    <input value=""@Model.List.SubmitDate.Value.ToString(""t"")""/>
                    <div class=""border""></div>
                  </div>
                  Uhr
                </div>
              }
            </div>
          </div>
        </div>
        <div>
          <div class=""row space"">
            <div class=""row"">
              <span class=""label space-right"">B</span>
              <div>
                <h2 class=""inline"">Kandidaturen</h2>
                <span>(Bitte in Blockschrift)</span>
              </div>
            </div>
            <span>Anzahl Sitze: @Model.ElectionNumberOfMandates</span>
          </div>
          <table class=""fullwidth"">
            <thead>
              <tr>
                <th rowspan=""2"">Nr.</th>
                <th rowspan=""2"" style=""width: 3cm"">Name</th>
                <th rowspan=""2"" style=""width: 3cm"">Vorname</th>
                <th rowspan=""2"">
                  <span class=""upright"">Geschlecht (m/w)</span>
                </th>
                <th colspan=""3"" class=""bot-no-border"">Geburtsdatum</th>
                <th class=""bot-no-border"" style=""width: 4cm;"">Beruf</th>
                <th colspan=""3"" class=""bot-no-border"">Adresse</th>
                <th colspan=""2"" class=""bot-no-border"">Heimatort/e</th>
                <th rowspan=""2""><span class=""upright"">Bisher</span></th>
                @if (!Model.ListIsDraft)
                {
                  <th rowspan=""2"" style=""width: 3.5cm"">
                    Unterschrift<span class=""super small"">1)</span><br />der Kandidierenden
                  </th>
                }
                <th rowspan=""2"" style=""width: .2cm"">Kontrolle (leer lassen)</th>
              </tr>
              <tr class=""top-no-border"">
                <th><span class=""upright"">Tag</span></th>
                <th><span class=""upright"">Monat</span></th>
                <th><span class=""upright"">Jahr</span></th>
                <th style=""width: 3.5cm;"">
                  inkl. allfällige Titel und weitere Bezeichnungen für
                  Stimmzettel
                </th>
                <th style=""width: 3cm;"">Strasse/Nr.</th>
                <th>PLZ</th>
                <th>Wohnort</th>
                <th style=""width: 3cm;""></th>
                <th>Kt.</th>
              </tr>
            </thead>
            <tbody>
            @foreach (var candidate in Model.List.Candidates)
            {
              <tr>
                <td class=""filled right"">@candidate.Index</td>
                <td>@(string.IsNullOrEmpty(candidate.BallotFamilyName) ? candidate.FamilyName : candidate.BallotFamilyName)</td>
                <td>@(string.IsNullOrEmpty(candidate.BallotFirstName) ? candidate.FirstName : candidate.BallotFirstName)</td>
                <td class=""center"">
                  @switch (candidate.Sex)
                  {
                    case SexType.Female:
                      <span>w</span>
                      break;
                    case SexType.Male:
                      <span>m</span>
                      break;
                  }
                </td>
                <td class=""center"">@candidate.DateOfBirth.Day</td>
                <td class=""center"">@candidate.DateOfBirth.Month</td>
                <td class=""center"">@candidate.DateOfBirth.Year</td>
                <td>@candidate.OccupationalTitle</td>
                <td>@candidate.Street @candidate.HouseNumber</td>
                <td>@candidate.ZipCode</td>
                <td>@candidate.Locality</td>
                <td class=""right"">@candidate.Origin</td>
                <td>@candidate.OriginCanton</td>
                <!-- Bisher -->
                <td></td>
                <!-- Unterschriftsfeld -->
                @if (!Model.ListIsDraft) 
                {
                  <td></td>
                }
                <td class=""filled""></td>
              </tr>
            }
            </tbody>
          </table>
        </div>
        <div class=""row space space-bottom"">
          <div>
            Vertretung des Wahlvorschlags durch Unterzeichner/in Nr.
            <div class=""input inline-input"">
              <input />
              <div class=""border""></div>
            </div>
          </div>
          <div><span class=""bold"">oder </span></div>
          <div>
            Name und Vorname
            <div class=""input inline-input w-16"">
              <input value=""@Model.ListCreatedBy.Firstname @Model.ListCreatedBy.Lastname"" />
              <div class=""border""></div>
            </div>
            E-Mail:
            <div class=""input inline-input"">
              <input value=""@Model.ListCreatedBy.Emails.FirstOrDefault(e => e.Primary)?.Email""/>
              <div class=""border""></div>
            </div>
          </div>
        </div>
        <div class=""row space space-bottom""> 
          <div>
            Stellvertretung des Wahlvorschlags d. Unterzeichner/in Nr.
            <div class=""input inline-input"">
              <input />
              <div class=""border""></div>
            </div>
          </div>
          <div><span class=""bold"">oder </span></div>
          <div>
            Name und Vorname
            <div class=""input inline-input w-16"">
              <input value=""@Model.ListDeputy?.Firstname @Model.ListDeputy?.Lastname""/>
              <div class=""border""></div>
            </div>
            E-Mail:
            <div class=""input inline-input"">
              <input value=""@Model.ListDeputy?.Emails.FirstOrDefault(e => e.Primary)?.Email""/>
              <div class=""border""></div>
            </div>
          </div>
        </div>
        <div class=""space-bottom"">
          Vertretung des Wahlvorschlags sowie deren Stellvertretung sind
          gegenüber den zuständigen Amtsstellen von Kanton und Bund berechtigt
          und verpflichtet, allenfalls nötige Erklärungen zur Bereinigung von
          Anständen oder Unklarheiten im Namen aller Unterzeichnenden
          rechtsverbindlich abzugeben (BPR Art. 25 Abs. 2). Wo eine klare
          Bezeichnung fehlt, kommt diese Aufgabe der erst- und der
          zweitunterzeichnenden Person zu.
        </div>
        <div class=""row stretch"">
          <span class=""super small space-right"">1)</span>
          <div class=""hint"">
            mit der Unterschrift erklärt der Kandidat oder die Kandidatin, dass
            er/sie dem Wahlvorschlag zustimmt und die Angaben zu seiner/ihrer
            Person richtig sind.<br />Massgebend sind die Verhältnisse am
            Wahltag. Nachträgliche Änderungswünsche können nicht berücksichtigt
            werden.
          </div>
          <div class=""grow version hint"">Version 1.0</div>
        </div>
      </main>
    </div>
  </body>
</html>
", Filename = "@Model.Election.Name - Kandidaten.pdf", Format = 0, Landscape = true, Type = 0 }
                    );
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.BallotDocument", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("Documents")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.Candidate", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.List", "List")
                        .WithMany("Candidates")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.DomainOfInfluenceElection", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.DomainOfInfluence", "DomainOfInfluence")
                        .WithMany("ParticipatingElections")
                        .HasForeignKey("DomainOfInfluenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("DomainsOfInfluence")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.InfoText", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("InfoTexts")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.List", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Election", "Election")
                        .WithMany("Lists")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eawv.Service.DataAccess.Entities.ListUnion", "ListSubUnion")
                        .WithMany("SubUnionLists")
                        .HasForeignKey("ListSubUnionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eawv.Service.DataAccess.Entities.ListUnion", "ListUnion")
                        .WithMany("UnionLists")
                        .HasForeignKey("ListUnionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.ListUnion", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.List", "RootList")
                        .WithOne("RootListUnion")
                        .HasForeignKey("Eawv.Service.DataAccess.Entities.ListUnion", "RootListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eawv.Service.DataAccess.Entities.MarkedElement", b =>
                {
                    b.HasOne("Eawv.Service.DataAccess.Entities.Candidate", "Candidate")
                        .WithMany("MarkedElements")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
