// (c) Copyright by Abraxas Informatik AG
// For license information see LICENSE file

using System.Diagnostics.CodeAnalysis;

// Suppress code analysis warnings for autogenerated code under Eawv.Service.Migrations
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1118:Parameter should not span multiple lines", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1028:Code should not contain trailing whitespace", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1122:Use string.Empty for empty strings", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("Simplification", "RCS1021:Simplify lambda expression.", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1111:Closing parenthesis should be on line of last parameter", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1137:Elements should have the same indentation", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
[assembly: SuppressMessage("Redundancy", "RCS1037:Remove trailing white-space.", Justification = "Autogenerated Migrations will not be cleaned up.", Scope = "namespaceanddescendants", Target = "~N:Eawv.Service.Migrations")]
